---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dco/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp -R src/* $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH
    - /bin/cp postcss.config.js $DEPLOYPATH
    - /bin/cp babel.config.json $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp .env.production $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
 