version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - NODE_ENV=production
    networks:
      - gatwick_net

networks:
  gatwick_net:
    driver: bridge 